"use client";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import theme from "@/app/components/utils/theme";
import { ColorModeScript } from "@chakra-ui/react";

import { Providers } from "../app/providers";
import { BlogProvider } from "../../context/blog-context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <BlogProvider>
          <Providers>
            <ColorModeScript initialColorMode={theme.config.initialColorMode} />
            {children}
          </Providers>
        </BlogProvider>
      </body>
    </html>
  );
}
